### ISSUE TITLE
[服务端] API Spec

### ISSUE THREAD

**Issue by terryoy** [szdiy/duo#1]
需要 @atommann 这边确认一下：

1. 能提供什么样的数据给服务端，频率、数据量如何。(数据采集）
2. 希望服务端呈现什么样的数据或图标。（数据呈现）

**Comment by atommann** [comment]
1. 很久以前，在柴火酿啤酒时，我们用过简单的 HTTP GET 方法，把数据嵌入在 URL 里，服务器端从 URL 里截取数据。还有一个方法是 POST.我很久没有研究 IoT 方面的最新技术，但听说应该用 MQTT. 

每 10 分钟传一次数据给服务器。

数据量不大。电表本身的数据非常多，我们只传我们感兴趣的数据。如，此时的总度数是 3988.00 度，10 分钟之后，再传总度数 3988.30 度...

2. 网页显示一个 canvas，X 轴是时间，Y 轴是空间用电功率的变化情况。以曲线表示。

还需要显示的：
* 显示实时的电表总度数
* 在某天的一个固定时间，显示一天的用电量

**Comment by terryoy** [comment]
用HTTP的好处是服务端的技术栈统一，而当时选用HTTP GET而不是POST的话，应该也是为了客户端尽量简单。

所以三个选项的评估是：
1. HTTP GET，无任何握手流程，只要有请求就更新数据到数据库，也无法验证真伪。
2. HTTP POST，原则上跟HTTP GET类似，但是可以传的数据包大一些，数据结构也可以复杂些，比如说如果如果客户端有一个数组的数据要发过来，就可以通过这种方式。但是HTTP POST需要包含更多的HEADER（其实也不是很难）
3. MQTT应该是一个完整的协议栈，具体有什么针对性的特性需要再调研。但对服务端来说是提高了复杂性，因为要另外实现一个MQTT的服务。

总上述，为简单起见可以先用HTTP GET，如果客户端有时钟的话，可以带上时间戳最好，这样保证受到的数据可以推算得出时序。

根据你的描述来看，数据包大约含以下数据：

```js
{
  total: 3988.00, // 总度数
  timestamp: 1231029318, // 一个整数时间戳(epoch time)
}
```

图表需求：
1. 总功率变化曲线（实时/历史）

其他信息：
某个时间点的总度数（当前/某天某时）

Am I right?

**Comment by atommann** [comment]
可以从电表里读取时间，而且是很准确的。ESP8266 还可以用 NTP 取时间。关于服务器 API, 我需要在 ESP8266 上写一个十分简单的程序，来模拟发送数据，我想看看目前有什么较好的传送方案。

**Comment by atommann** [comment]
MQTT 是双向的，而我们只需单方向从 client 向服务器端发数据，因此 HTTP GET 或 POST 就可以。以前我试过[data.sparkfun.com](https://data.sparkfun.com/) 的服务。在 ESP8266 的代码里加上一个 private key，这样数据就不会被人捣乱了。

**Comment by terryoy** [comment]
要看看客户端是否支持ssl，好像esp8266做这个不太方便？ 如果没有ssl的话，有private key和没private key没啥区别（反正都是明文传输），最多你带上一个node_id来标识你是哪个设备。

**Comment by atommann** [comment]
有 SSL 支持，https://github.com/SuperHouse/esp-open-rtos

**Comment by terryoy** [comment]
那好。先按https get的方式处理。

API Upload:
http://api.szdiy.org/duo/upload?node=<node_id>&total=<total>&time=<timestamp>
参数解释：
 - node_id：设备id
 - total: 电表读数
 - time: epoch time（如果无提供则取服务器时间）

**Comment by NalaGinrut** [comment]
api.szdiy.org已经被其他框架占用了，请使用api-temp.szdiy.org，不然之前做的一些东西会受到影响

**Comment by terryoy** [comment]
改个location即可，我有考虑过这个问题。

发自我的 iPhone

**Comment by terryoy** [comment]
在nginx里配了api.szdiy.org/duo的路径，禅师你看看对现有对框架有没有影响，应该是没有影响的。
http://api.szdiy.org/duo/index.html

之后我再在location /duo里加上upstream即可调用django的服务。

2017-04-30 1:31 GMT+08:00 Mu Lei <notifications@github.com>:

**Comment by NalaGinrut** [comment]
这个是可以的，反正就是重定位到另一个端口。
另外要说一下，最好重定位到unix socket，也就是文件形式的socket，不要占用socket端口

**Comment by atommann** [comment]
@terryoy 如果别人知道 API 路径格式，则他写个脚本就能向服务器写假数据，对吗？ https://api.szdiy.org/duo/upload?node=001&total=3988.00&time=1231029318

怎样判定数据真的是从电表传来的？

**Comment by terryoy** [comment]
是的，所以后期我们可以再考虑加上一定的认证方式

发自我的 iPhone

**Comment by NalaGinrut** [comment]
需要设计token的

**Comment by terryoy** [comment]
@atommann
是的，所以我们想要https来加密通信，同时给节点分配token，通过token来识别是否真正节点上传的数据。不过这个可以晚一步做，先完成主流程。

2017-05-03 0:12 GMT+08:00 Mu Lei <notifications@github.com>:

**Comment by zend** [comment]
token的设计可以考虑仿照OAuth协议。有这几步：

1. 分配appid / appsecret，appid在我们这里可以是nodeID
1. 凭借appid + appsecret向服务器换取access_token，3600秒内有效
1. 用access_token来验证请求是否合法

好处是可以减少核心密码在网络传输的次数（3600t秒才1次），而大部分请求用一个短期有效的access_token取代，防止https流量抓取样本分析破解。

**Comment by NalaGinrut** [comment]
好的，有问题会说出来的，没有说就当作没有问题吧

2017-07-19 11:52 GMT+08:00 ZENGHAI LIANG <notifications@github.com>:
