### ISSUE TITLE
mbedtls_ssl_read 读 szdiy 网站返回错误

### ISSUE THREAD

**Issue by atommann** [szdiy/duo#4]
尝试修改一个 HTTPS GET 例子和 szdiy.org 通讯。

[http_get_mbedtls 例子](https://github.com/SuperHouse/esp-open-rtos/blob/master/examples/http_get_mbedtls/http_get_mbedtls.c)
* 修改了 cert.c 中的证书内容 
* 修改了 http_get_mbedtls.c 中的 url 为 szdiy.org

和服务器通讯的记录打印如下：

```
Starting again!
top of loop, free heap = 24140
  . Connecting to szdiy.org:443...
 ok
  . Performing the SSL/TLS handshake...
 ok
  . Verifying peer X.509 certificate... ok
  > Write to server: 48 bytes written

GET https://szdiy.org HTTP/1.1
Host: szdiy.org

  < Read from server:
failed
  ! mbedtls_ssl_read returned -29184



Last error was: -29184 - SSL - An invalid SSL record was received
```
读取服务器响应的代码开始于 http_get_mbedtls.c 第 262 行。
错误信息是 An invalid SSL record was received
但，原始的例子是没问题的。

**Comment by terryoy** [comment]
看了一下szdiy.org的证书，好像是禅师的nalaginrut.com的证书，是nginx配置有问题？

2017-05-02 7:24 GMT+08:00 atommann <notifications@github.com>:

**Comment by terryoy** [comment]
@NalaGinrut szdiy.org用的是哪个配置？ 我找不到。建议建一个default的server。

**Comment by NalaGinrut** [comment]
我忘了，问下阿丰

**Comment by terryoy** [comment]
我把szdiy.org上的https证书换成了szdiy.org了，浏览器里看没问题。@atommann 你再试试？

另外，禅师你是不是有个脚本自动续期证书的？我用letsencrypt更新的szdiy.org证书，有效期只到2017年7月31日。这个目前是遗留的问题。

2017-05-02 10:16 GMT+08:00 Mu Lei <notifications@github.com>:

**Comment by atommann** [comment]
@terryoy 我晚上回家试(目前在长安镇出差)。

想到几点：
* 那个例子里，返回的是一个很小的页面，而我去 GET szdiy.org 的根目录，会返回整个页面，会不会和这个有关系。方法：试着访问一个更小的页面。
* 试另一个网站，看结果如何。
* 用 openssl s_client -connect szdiy.org:443 然后手动 GET 是可以正常返回的。

**Comment by atommann** [comment]
@terryoy 我试了 GET https://api.szdiy.org/duo 就可以正常读取服务器的返回数据了。但把代码改成 GET https://szdiy.org 就重现最初的错误，看样子是 buffer 不够大造成的。

因为证书用的是 chain 的最后那个，所以代码里证书不用修改。

但发现一个新的 issue: 就是当 ESP8266 接收到数据，显示 It works! - Duo Project 完成之后，要等很久才能进行下一次通讯。打印 It works! - Duo Project 之后的代码如下：

```
        mbedtls_ssl_close_notify(&ssl);

    exit:
        mbedtls_ssl_session_reset(&ssl);
        mbedtls_net_free(&server_fd);
```

会是服务器端的设置造成的吗？我看到返回的数据有 Connection: keep-alive 字样，原本的http_get_mbedtls 例子服务器返回中有 Connection: close 字样。这个我研究一下开另一个 issue.

下面是通讯的打印记录。

```
It works! - Duo Project



successes = 13 failures = 0
10... 
9... 
8... 
7... 
6... 
5... 
4... 
3... 
2... 
1... 
0... 

Starting again!
top of loop, free heap = 24668
  . Connecting to szdiy.org:443...
 ok
  . Performing the SSL/TLS handshake...
 ok
  . Verifying peer X.509 certificate... ok
  > Write to server: 57 bytes written

GET https://api.szdiy.org/duo/ HTTP/1.1
Host: szdiy.org

  < Read from server:
 329 bytes read

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Tue, 02 May 2017 14:40:38 GMT
Content-Type: text/html
Content-Length: 24
Last-Modified: Tue, 02 May 2017 03:37:30 GMT
Connection: keep-alive
ETag: "5907fefa-18"
Expires: Wed, 03 May 2017 02:40:38 GMT
Cache-Control: max-age=43200
Accept-Ranges: bytes

It works! - Duo Project
```

**Comment by atommann** [comment]
试了一下 GET https://api.szdiy.org/duo/upload?node=001&total=3988.00&time=1231029318 也 OK 的，但还是有间隔时间长的问题。

```
Starting again!
top of loop, free heap = 24668
  . Connecting to szdiy.org:443...
 ok
  . Performing the SSL/TLS handshake...
 ok
  . Verifying peer X.509 certificate... ok
  > Write to server: 102 bytes written

GET https://api.szdiy.org/duo/upload?node=001&total=3988.00&time=1231029318 HTTP/1.1
Host: szdiy.org

  < Read from server:
 322 bytes read

HTTP/1.1 404 Not Found
Server: nginx/1.6.2
Date: Tue, 02 May 2017 15:09:46 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

**Comment by terryoy** [comment]
如果是跟证书无关，那我先恢复到nalaginrut.com的证书了
