### ISSUE TITLE
[branch/master] Naming Conflict

### ISSUE THREAD

**Issue by terryoy** [szdiy/duo#9]
https://github.com/szdiy/duo/commit/418982238ede7bdf9c89bbecbaac8de32f703a17

@atommann 每次checkout下来这个都会有uncommit change，原因是有两个文件同名（仅大小写不一样），所以我改了其中一个文件名，但发现有两个文件的内容是不一样的，你检查一下看怎么修复这个。

**Comment by atommann** [comment]
@terryoy 现在没问题了。用来生成文件的一个 perl 脚本和它自己生成的文件同名了。
